//
//Copyright 2023 Derrick J Wippler
//
//Licensed under the MIT License, you may obtain a copy of the License at
//
//https://opensource.org/license/mit/ or in the root of this code repo
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: demo/demo.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RenderPixelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Complexity float64 `protobuf:"fixed64,1,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Height     int64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width      int64   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	I          int64   `protobuf:"varint,4,opt,name=i,proto3" json:"i,omitempty"`
	J          int64   `protobuf:"varint,5,opt,name=j,proto3" json:"j,omitempty"`
}

func (x *RenderPixelRequest) Reset() {
	*x = RenderPixelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderPixelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPixelRequest) ProtoMessage() {}

func (x *RenderPixelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPixelRequest.ProtoReflect.Descriptor instead.
func (*RenderPixelRequest) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{2}
}

func (x *RenderPixelRequest) GetComplexity() float64 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

func (x *RenderPixelRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderPixelRequest) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderPixelRequest) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *RenderPixelRequest) GetJ() int64 {
	if x != nil {
		return x.J
	}
	return 0
}

type RenderPixelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Gray represents an 8-bit grayscale color.
	Gray int64 `protobuf:"varint,1,opt,name=gray,proto3" json:"gray,omitempty"`
}

func (x *RenderPixelResponse) Reset() {
	*x = RenderPixelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderPixelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPixelResponse) ProtoMessage() {}

func (x *RenderPixelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPixelResponse.ProtoReflect.Descriptor instead.
func (*RenderPixelResponse) Descriptor() ([]byte, []int) {
	return file_demo_demo_proto_rawDescGZIP(), []int{3}
}

func (x *RenderPixelResponse) GetGray() int64 {
	if x != nil {
		return x.Gray
	}
	return 0
}

var File_demo_demo_proto protoreflect.FileDescriptor

var file_demo_demo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x64, 0x75, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2c, 0x0a, 0x10, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7e,
	0x0a, 0x12, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x78, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x69,
	0x12, 0x0c, 0x0a, 0x01, 0x6a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6a, 0x22, 0x29,
	0x0a, 0x13, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x72, 0x61, 0x79, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x68, 0x2d, 0x72, 0x70, 0x63, 0x2f,
	0x64, 0x75, 0x68, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_demo_demo_proto_rawDescOnce sync.Once
	file_demo_demo_proto_rawDescData = file_demo_demo_proto_rawDesc
)

func file_demo_demo_proto_rawDescGZIP() []byte {
	file_demo_demo_proto_rawDescOnce.Do(func() {
		file_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_demo_proto_rawDescData)
	})
	return file_demo_demo_proto_rawDescData
}

var file_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_demo_demo_proto_goTypes = []interface{}{
	(*SayHelloRequest)(nil),     // 0: duh.v1.SayHelloRequest
	(*SayHelloResponse)(nil),    // 1: duh.v1.SayHelloResponse
	(*RenderPixelRequest)(nil),  // 2: duh.v1.RenderPixelRequest
	(*RenderPixelResponse)(nil), // 3: duh.v1.RenderPixelResponse
}
var file_demo_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_demo_proto_init() }
func file_demo_demo_proto_init() {
	if File_demo_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderPixelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderPixelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_demo_proto_goTypes,
		DependencyIndexes: file_demo_demo_proto_depIdxs,
		MessageInfos:      file_demo_demo_proto_msgTypes,
	}.Build()
	File_demo_demo_proto = out.File
	file_demo_demo_proto_rawDesc = nil
	file_demo_demo_proto_goTypes = nil
	file_demo_demo_proto_depIdxs = nil
}
